import './globals.css';
import { Noto_Sans_TC } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import DataProvider from '@/components/DataProvider';
import React from 'react';

const inter = Noto_Sans_TC({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataProvider />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
