"use client";
import './globals.css';
import { Noto_Sans_TC,Bebas_Neue,Russo_One } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import DataProvider from '@/components/DataProvider';
import React from 'react';
import { SnackbarProvider } from 'notistack';

const inter = Noto_Sans_TC({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});
const outer = Bebas_Neue({
  subsets: ['latin'],
  weight: '400'
});
const tester = Russo_One({
  subsets: ['latin'],
  weight: '400'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={tester.className}>
      <SnackbarProvider maxSnack={2}> 
        <DataProvider />
        <Header />
        {children}
        <Footer />
      </SnackbarProvider>
      </body>
    </html>
  );
}
